#!/usr/bin/env bash
# 1. Makes sure the script is running from the root directory
# 2. Run a python script, adding the current working directory to the PYTHONPATH.

if [ ! -f "config.json" ] ;
then
  echo "Please run this script inside the project root directory."
  exit 1
fi

num_args=`expr $# - 1`
for k in $(seq 0 $num_args); do
  kp1=`expr $k + 1`
  args[$k]="\"${!kp1}\""
done

cmd="PYTHONPATH=\${PYTHONPATH}:. python ${args[@]}"
>&2 echo "Running: $cmd"
eval "exec env $cmd"

# vim: set ft=bash
